#pragma once

//Clear variables we plan to use that might be set elsewhere
#undef AUTO_SHIFT_MODIFIERS
#undef AUTO_SHIFT_TIMEOUT
#undef AUTO_SHIFT_TIMEOUT_PER_KEY
#undef AUTO_SHIFT_NO_SETUP
#undef AUTO_SHIFT_REPEAT
#undef AUTO_SHIFT_REPEAT_PER_KEY 
#undef AUTO_SHIFT_NO_AUTO_REPEAT
#undef AUTO_SHIFT_NO_AUTO_REPEAT_PER_KEY 

#undef NO_AUTO_SHIFT_SPECIAL
#undef NO_AUTO_SHIFT_TAB
#undef NO_AUTO_SHIFT_SYMBOLS
#undef NO_AUTO_SHIFT_NUMBERIC
#undef NO_AUTO_SHIFT_ALPHA
#undef AUTO_SHIFT_ENTER

//Set common configuration for all keyboards
#define AUTO_SHIFT_TIMEOUT 140
#define AUTO_SHIFT_TIMEOUT_PER_KEY
#define AUTO_SHIFT_REPEAT
#define NO_AUTO_SHIFT_NUMERIC
