#pragma once

/* SPI & PMW3360 settings. */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP22
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP23
#define POINTING_DEVICE_CS_PIN GP21

#define MASTER_RIGHT

#define SPLIT_POINTING_ENABLE

#define POINTING_DEVICE_RIGHT
