name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: t4corun/.github/.github/workflows/qmk_userspace_build.yml@nontree
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master

  publish:
    name: 'QMK Userspace Publish'
    uses: t4corun/.github/.github/workflows/qmk_userspace_publish.yml@nontree
    if: always() && !cancelled()
    needs: build
